### ISSUE TITLE
deletes file content on save

### ISSUE THREAD

**Issue by ganluin** [AnWeber/atom-htmltidy#12]
Hi,
I am running Atom 1.7.4 and atom-htmltidy  5.1.0.

When i save a php file an info window pops up with the message:
atom-htmltidy: tag count changed
1 tags missing.

and then the contents of the file is completely deleted.
I have tried uninstalling and reinstalling both atom and the atom-htmltidy package.
I also deleted the hidden atom directory in my home directory.

**Comment by AnWeber** [comment]
hello,

please add your htmltidy options and one file which cause the issue. 
I think in your options the setting show-errors is missing. If this option is missing all errors while formatting are ignored and the content will be deleted. This is just my first guess, but to detect the real issue I need your input.

Thanks.

**Comment by AnWeber** [comment]
the extension is just a wrapper for tidyhtml command line. Is the
formatting of your file on the command line working (
http://api.html-tidy.org/tidy/tidylib_api_5.2.0/tidy_cmd.html)?

ganluin notifications@github.com schrieb am So., 29. Mai 2016 um
07:30 Uhr:

**Comment by AnWeber** [comment]
no feedback
