### ISSUE TITLE
How to set default options?

### ISSUE THREAD

**Issue by RobbieTheWagner** [AnWeber/atom-htmltidy#13]
I see there is a default config box, but is this supposed to be a file path or rules pasted directly in? Please advise of the format so I can use it. I tried pasting `"indent":true"` in the box and nothing happened.

**Comment by AnWeber** [comment]
the extension expects a json format. {indent":true} should be fine. I will
update the documetation

Robert Wagner notifications@github.com schrieb am Fr., 29. Juli 2016 um
00:27 Uhr:

**Comment by RobbieTheWagner** [comment]
Hi @AnWeber. I tried your suggestion, but it does not seem to indent my file on save

**Comment by RobbieTheWagner** [comment]
`{"indent":"auto", "indent-spaces":2}` seems to work. It doesn't format like I want it to, but it does format now. Trying to figure out how to configure it for Ember HTMLBars
