### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by juzzyo** [AnWeber/atom-htmltidy#2]
[Enter steps to reproduce below:]
1. press control+alt+1

**Atom Version**: 1.3.1
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-htmltidy](https://github.com/AnWeber/atom-htmltidy) package, v1.5.0
### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:298

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at new TidyWorker (/Users/justinoneill/.atom/packages/atom-htmltidy/lib/tidywrapper.js:26:31)
    at tidy (/Users/justinoneill/.atom/packages/atom-htmltidy/lib/tidywrapper.js:75:16)
    at format (/Users/justinoneill/.atom/packages/atom-htmltidy/lib/init.js:98:9)
    at atom-workspace.<anonymous> (/Users/justinoneill/.atom/packages/atom-htmltidy/lib/init.js:80:5)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -3:38.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:37.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:37.6.0 core:paste (atom-text-editor.editor.is-focused)
     -3:36.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:34 core:backspace (atom-text-editor.editor.is-focused)
     -3:33.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:33.1.0 core:paste (atom-text-editor.editor.is-focused)
     -3:32.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:30.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:30.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:29.8.0 core:paste (atom-text-editor.editor.is-focused)
     -3:29.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:44.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:39.7.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -1:37.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.6.0 atom-htmltidy:format (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "language-jsx",
      "jshint",
      "jscs-fixer",
      "linter-jscs",
      "merge-conflicts"
    ],
    "ignoredNames": [
      ".git",
      ".gitignore",
      ".DS_Store",
      "._*",
      "Thumbs.db"
    ],
    "projectHome": "/Users/justinoneill/dev"
  }
}
```
### Installed Packages

``` coffee
# User
atom-htmltidy, v1.5.0
atom-jade, v0.3.0
color-picker, v2.0.13
file-types, v0.5.1
language-jade, v0.6.2
language-javascript-jsx, v0.3.7
language-squarespace, v0.4.0
minimap, v4.16.0

# Dev
No dev packages
```

**Comment by AnWeber** [comment]
A quick search for this type of error on the web, is hinting to a file
permission problem. please check if you have all needed file permission to
run tidy with your input file in the command line.

juzzyo notifications@github.com schrieb am Di., 15. Dez. 2015 um
05:23 Uhr:

**Comment by juzzyo** [comment]
Hi Andreas,

Modified permissions on the file in question and still no dice.

-rwxrwxrwx   1 myid  staff    147 16 Dec 10:36 news-national.php

Am I missing something really obvious?

On 15 December 2015 at 17:47, Andreas Weber notifications@github.com
wrote:

> A quick search for this type of error on the web, is hinting to a file
> permission problem. please check if you have all needed file permission to
> run tidy with your input file in the command line.
> 
> juzzyo notifications@github.com schrieb am Di., 15. Dez. 2015 um
> 05:23 Uhr:
> 
> > [Enter steps to reproduce below:]
> > 1. press control+alt+1
> > 
> > _Atom Version_: 1.3.1
> > _System_: Mac OS X 10.10.5
> > _Thrown From_: atom-htmltidy https://github.com/AnWeber/atom-htmltidy
> > package, v1.5.0
> > Stack Trace
> > 
> > Uncaught Error: spawn EACCES
> > 
> > At internal/child_process.js:298
> > 
> > Error: spawn EACCES
> > at exports._errnoException (util.js:837:11)
> > at ChildProcess.spawn (internal/child_process.js:298:11)
> > at Object.exports.spawn (child_process.js:351:9)
> > at new TidyWorker
> > (/Users/justinoneill/.atom/packages/atom-htmltidy/lib/tidywrapper.js:26:31)
> > at tidy
> > (/Users/justinoneill/.atom/packages/atom-htmltidy/lib/tidywrapper.js:75:16)
> > at format
> > (/Users/justinoneill/.atom/packages/atom-htmltidy/lib/init.js:98:9)
> > at atom-workspace.<anonymous>
> > (/Users/justinoneill/.atom/packages/atom-htmltidy/lib/init.js:80:5)
> > at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent
> > (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
> > at
> > /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
> > at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent
> > (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
> > at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent
> > (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
> > at
> > WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown
> > (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
> > at HTMLDocument.<anonymous>
> > (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
> > 
> > Commands
> > 
> > -3:38.3.0 core:backspace (atom-text-editor.editor.is-focused)
> > -3:37.9.0 editor:newline (atom-text-editor.editor.is-focused)
> > -3:37.6.0 core:paste (atom-text-editor.editor.is-focused)
> > -3:36.7.0 editor:newline (atom-text-editor.editor.is-focused)
> > -3:34 core:backspace (atom-text-editor.editor.is-focused)
> > -3:33.4.0 editor:newline (atom-text-editor.editor.is-focused)
> > -3:33.1.0 core:paste (atom-text-editor.editor.is-focused)
> > -3:32.9.0 editor:newline (atom-text-editor.editor.is-focused)
> > -3:30.6.0 core:backspace (atom-text-editor.editor.is-focused)
> > -3:30.2.0 editor:newline (atom-text-editor.editor.is-focused)
> > -3:29.8.0 core:paste (atom-text-editor.editor.is-focused)
> > -3:29.5.0 editor:newline (atom-text-editor.editor.is-focused)
> > 2x -2:44.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
> > -1:39.7.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
> > -1:37.6.0 core:select-all (atom-text-editor.editor.is-focused)
> > -0:00.6.0 atom-htmltidy:format (atom-text-editor.editor.is-focused)
> > 
> > Config
> > 
> > {
> > "core": {
> > "themes": [
> > "atom-dark-ui",
> > "base16-tomorrow-dark-theme"
> > ],
> > "disabledPackages": [
> > "language-jsx",
> > "jshint",
> > "jscs-fixer",
> > "linter-jscs",
> > "merge-conflicts"
> > ],
> > "ignoredNames": [
> > ".git",
> > ".gitignore",
> > ".DS_Store",
> > "._*",
> > "Thumbs.db"
> > ],
> > "projectHome": "/Users/justinoneill/dev"
> > }
> > }
> > 
> > Installed Packages
> > 
> > # User
> > 
> > atom-htmltidy, v1.5.0
> > atom-jade, v0.3.0
> > color-picker, v2.0.13
> > file-types, v0.5.1
> > language-jade, v0.6.2
> > language-javascript-jsx, v0.3.7
> > language-squarespace, v0.4.0
> > minimap, v4.16.0
> > 
> > # DevNo dev packages
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/AnWeber/atom-htmltidy/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AnWeber/atom-htmltidy/issues/2#issuecomment-164661372
> .

## 

_Justin O'Neill_  |  Co-Founder, Product Director

_Quixo Facto_
Mobile: +61 401 731 568
Email: justin@quixofacto.com
Web: http://www.quixofacto.com/
Justin on Linkedin: http://www.linkedin.com/in/juzzyo
Quixo Facto on Linkedin: http://www.linkedin.com/company/quixo-facto/

_Quixomatic - our flagship product_
Web: http://www.quixomatic.com/
Facebook: http://www.facebook.com/Quixomatic
LinkedIn:
http://www.linkedin.com/company/quixo-facto/quixomatic-1729931/product

**Comment by AnWeber** [comment]
did you set the file permission on the tidy executable in my package?

_packagefolder_\atom-htmltidy\lib\bin\linux\tidy

I think it is missing the execute privlige. It is only a wild guess from an
old win user. Please check this file as well. I will check the atom
documentation if it contains some help regarding to file permissions after
installation.

thanks.

juzzyo notifications@github.com schrieb am Mi., 16. Dez. 2015 um
01:06 Uhr:

**Comment by AnWeber** [comment]
I made a update (v.1.6). In this update I changed the file permission of tiny to allow execution. Please update and test. Please give feedback if it is working.

**Comment by juzzyo** [comment]
Works like a dream! Thank you so much!!

On 17 December 2015 at 06:55, Andreas Weber notifications@github.com
wrote:

> I made a update (v.1.6). In this update I changed the file permission of
> tiny to allow execution. Please update and test. Please give feedback if it
> is working.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AnWeber/atom-htmltidy/issues/2#issuecomment-165225626
> .

## 

_Justin O'Neill_  |  Co-Founder, Product Director

_Quixo Facto_
Mobile: +61 401 731 568
Email: justin@quixofacto.com
Web: http://www.quixofacto.com/
Justin on Linkedin: http://www.linkedin.com/in/juzzyo
Quixo Facto on Linkedin: http://www.linkedin.com/company/quixo-facto/

_Quixomatic - our flagship product_
Web: http://www.quixomatic.com/
Facebook: http://www.facebook.com/Quixomatic
LinkedIn:
http://www.linkedin.com/company/quixo-facto/quixomatic-1729931/product
