### ISSUE TITLE
wraps <pre> content

### ISSUE THREAD

**Issue by garretwilson** [AnWeber/atom-htmltidy#3]
I have XHTML5 content starting with:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html><html  lang="en-us"  xmlns="http://www.w3.org/1999/xhtml">
  <head>
```

Try as I might, I cannot stop atom-htmltidy from wrapping my `<pre>` tags. Here is my config:

```
{"input-xml" : true, "output-xml" : true, "indent" : true, "indent-with-tabs" : true, "wrap" : 0}
```

Here is sample input:

```
<figure>
  <pre> <kbd>munge-file --when now -v target-file.dat</kbd></pre>
</figure>
```

That gets changed to:

```
    <figure>
        <pre>

<kbd>munge-file --when now -v target-file.dat</kbd>
</pre>
    </figure>
```

Where are the newlines coming from?

**Comment by AnWeber** [comment]
the atom plugin is just a wrapper for [Tidy-HTML5](http://www.htacg.org/tidy-html5/), [Documentation](http://api.html-tidy.org/tidy/quickref_5.1.25.html).

Please visit this [issue](https://github.com/htacg/tidy-html5/issues/332). If it doesn't match please open an issue [here](https://github.com/htacg/tidy-html5/issues). 

Thanks
