### ISSUE TITLE
stop atom-htmltidy from saving file

### ISSUE THREAD

**Issue by garretwilson** [AnWeber/atom-htmltidy#4]
I use `Ctrl+ALt+1` to format a file. But the file is not marked as modified! Is atom-htmltidy automatically saving the file? I didn't ask for the file to be saved --- I only asked for it to be formatted.

**Comment by AnWeber** [comment]
Yes. At the moment atom-htmltidy always saves the file after formatting. If format on save is enabled the user expects a saved file after saving. When using CTRL-ALT+1 it is not useful. I will fix it in the next release.

**Comment by AnWeber** [comment]
I uploaded a new release v1.7.0. When using CTRL+ALT+1 the file will not saved after formatting.
