### ISSUE TITLE
atom Htmltidy

### ISSUE THREAD

**Issue by iviryxavyer** [AnWeber/atom-htmltidy#8]
I was having problems with this package, when  I want to save my files with "ctrl-s" trigger the package change my code and inject HTML code on the bottom of the document. please fix it.

**Comment by AnWeber** [comment]
Hello,
if you enable format on save the extension automatically formats your html code. if you have invalid html code like '<div><span></div>' tidy html formats it to valid html code (e.g <div><span></span></div>). That is a feature. 
If you don't want to format the code on save disable it in the settings. If the added code  is something like <html><body></body></html> then you can enable the setting enableDynamicBody, which automatically sets the 'show-body-only' option for the tidy html call.
If you need more help, I need more information like the html code producing your issue.
