### ISSUE TITLE
Inline PHP

### ISSUE THREAD

**Issue by xtrasimplicity** [AnWeber/atom-htmltidy#9]
Hi there,

Inline PHP is being encoded on save, which breaks the code. i.e.

`<a  href="#" class="apply-<?php echo $id; ?>Apply</a>` becomes `<a href="#" class="apply-&lt;?php echo $item; ?&gt;">Apply</a>`

Obviously, we can work around this  - but it is a little frustrating to have to do so.

Thanks! :)

**Comment by AnWeber** [comment]
Hello,

thanks for your question. I can reproduce your issue on the command line.

`tidy -config tidy.txt test.txt`

[tidy.txt](https://github.com/AnWeber/atom-htmltidy/files/174541/tidy.txt)
[test.txt](https://github.com/AnWeber/atom-htmltidy/files/174542/test.txt)

Unfortunately this means, it is an issue of [HTML Tidy](http://api.html-tidy.org/tidy/quickref_5.1.25.html).  This package is just a wrapper to this application. In the current version there is no option, to fix your issue. Please create a new issue in this [repository](https://github.com/htacg/tidy-html5/issues).

A solution in my code would be to automatically revert all occurrences of &lt;? and ?&gt; back to <? and ?>. But this idea feels really like a terrible hack and can produce some side effects.

What is your opinion?

**Comment by AnWeber** [comment]
I don't prefer a hacky solution. If there is an other idea to fix the issue, please reopen it. 

Thanks
